// Owns the marker-delimited block of config.h. Everything outside the markers is preserved
// byte-for-byte so hand-added #defines survive an editor write.
import type { OledSettings } from './persist';

const START = '// >>> editor-generated';
const END = '// <<< editor-generated';

/** What the board already gives us when the keymap config.h defines nothing: the CandyPad's
 *  own config.h sets OLED_TIMEOUT to 2 minutes, so defaulting to QMK's 60000 would silently
 *  halve the panel sleep on the first save. Brightness has no board override. */
const DEFAULTS: OledSettings = { brightness: 255, timeout: 120000 };

/** Matches a whole marker block, markers included, at line granularity. */
const BLOCK_RE = /^[ \t]*\/\/ >>> editor-generated[\s\S]*?^[ \t]*\/\/ <<< editor-generated[ \t]*$\n?/m;

const HEADER = '// SPDX-License-Identifier: GPL-2.0-or-later\n#pragma once\n';

export function renderOledBlock(oled: OledSettings): string {
  const brightness = clamp(oled.brightness, 0, 255, DEFAULTS.brightness);
  // One hour is far beyond any useful panel timeout and keeps the literal small.
  const timeout = clamp(oled.timeout, 0, 3_600_000, DEFAULTS.timeout);
  // #undef first: the board's own config.h already defines OLED_TIMEOUT, and redefining it
  // with different tokens is a `warning: "OLED_TIMEOUT" redefined` on every build.
  return [
    START,
    "// QMK's default is 255; the CandyPad panel is uncomfortably bright at full.",
    '#undef OLED_BRIGHTNESS',
    `#define OLED_BRIGHTNESS ${brightness}`,
    '// Milliseconds before the panel sleeps; 0 disables the timeout.',
    '#undef OLED_TIMEOUT',
    `#define OLED_TIMEOUT ${timeout}`,
    END,
    '',
  ].join('\n');
}

export function applyOledBlock(existing: string, oled: OledSettings): string {
  const block = renderOledBlock(oled);
  if (BLOCK_RE.test(existing)) return existing.replace(BLOCK_RE, block);
  // No markers: append rather than clobber whatever the file already holds.
  const base = existing.trim() === '' ? HEADER : existing.replace(/\n*$/, '\n');
  return `${base}\n${block}`;
}

export function parseOledBlock(existing: string): OledSettings {
  // Prefer the editor block: a #define outside it is the user's own and may be commented out.
  const scope = existing.match(BLOCK_RE)?.[0] ?? existing;
  return {
    brightness: readDefine(scope, 'OLED_BRIGHTNESS') ?? DEFAULTS.brightness,
    timeout: readDefine(scope, 'OLED_TIMEOUT') ?? DEFAULTS.timeout,
  };
}

function readDefine(text: string, name: string): number | undefined {
  const m = new RegExp(`^[ \\t]*#define[ \\t]+${name}[ \\t]+(\\d+)`, 'm').exec(text);
  return m?.[1] === undefined ? undefined : Number(m[1]);
}

function clamp(v: number, lo: number, hi: number, fallback: number): number {
  if (!Number.isFinite(v)) return fallback;
  return Math.min(hi, Math.max(lo, Math.round(v)));
}

// ── oled.c ────────────────────────────────────────────────────────────────────
// The body of candypad_render_default_user(), the weak hook the board's candypad_oled.c
// declares. Same marker contract as config.h: only what is between them is ours.

const BODY_RE = /^[ \t]*\/\/ >>> editor-generated[ \t]*\n([\s\S]*?)^[ \t]*\/\/ <<< editor-generated[ \t]*$/m;

const RULES_LINE = 'SRC += oled.c';

export function renderOledC(body: string): string {
  return [
    '// Generated by the CandyPad editor. The body between the markers is yours.',
    '#include QMK_KEYBOARD_H',
    '',
    '#ifdef OLED_ENABLE',
    'bool candypad_render_default_user(void) {',
    START,
    trimEnd(body),
    END,
    '}',
    '#endif',
    '',
  ].join('\n');
}

export function applyOledC(existing: string, body: string): string {
  if (!BLOCK_RE.test(existing)) return renderOledC(body);
  const block = `${START}\n${trimEnd(body)}\n${END}\n`;
  // Function replacement: a "$&" in the user's C would be a substitution pattern otherwise.
  return existing.replace(BLOCK_RE, () => block);
}

export function parseOledC(existing: string): string {
  return trimEnd(BODY_RE.exec(existing)?.[1] ?? '');
}

/** rules.mk content for the next save; null means "the file should not exist". */
export function applyRulesMk(existing: string | null, needed: boolean): string | null {
  const kept = (existing ?? '').split('\n').filter((l) => l.trim() !== RULES_LINE);
  while (kept.length && kept[kept.length - 1]!.trim() === '') kept.pop();
  if (needed) kept.push(RULES_LINE);
  return kept.length ? `${kept.join('\n')}\n` : null;
}

/** Braces and block comments only — a browser cannot compile C, and CI already does. */
export function checkOledC(body: string): string | null {
  let depth = 0;
  let inComment = false;
  for (let i = 0; i < body.length; i++) {
    const c = body[i]!;
    const next = body[i + 1];
    if (inComment) {
      if (c === '*' && next === '/') {
        inComment = false;
        i++;
      }
    } else if (c === '/' && next === '*') {
      inComment = true;
      i++;
    } else if (c === '/' && next === '/') {
      const nl = body.indexOf('\n', i);
      if (nl < 0) break;
      i = nl;
    } else if (c === '"' || c === "'") {
      i = endOfLiteral(body, i);
    } else if (c === '{') {
      depth++;
    } else if (c === '}' && --depth < 0) {
      return 'a "}" closes a block that was never opened';
    }
  }
  if (inComment) return 'a /* comment is never closed';
  if (depth > 0) return `${depth} "{" left unclosed`;
  return null;
}

function endOfLiteral(text: string, start: number): number {
  const quote = text[start];
  for (let i = start + 1; i < text.length; i++) {
    if (text[i] === '\\') i++;
    else if (text[i] === quote || text[i] === '\n') return i;
  }
  return text.length;
}

function trimEnd(s: string): string {
  return s.replace(/\s+$/, '');
}
