// Generated by Candypad Configurator
#pragma once

// Layers
#define DYNAMIC_KEYMAP_LAYER_COUNT 4

// OLED
#undef OLED_TIMEOUT
#define OLED_TIMEOUT 120000
#undef OLED_BRIGHTNESS
#define OLED_BRIGHTNESS 128

// Encoders
#define ENCODER_DEFAULT_POS 0x3  // 1:1 resolution
