// ============================================================
// Candypad QMK Keymap — generated by Candypad Configurator
// Flash with:  qmk compile -kb binepad/candypad -km my_keymap
// Docs: https://docs.qmk.fm
// ============================================================

#include QMK_KEYBOARD_H

// ── Layer indices ─────────────────────────────────────────
// ── Keycode compatibility shims ───────────────────────────
// Newer QMK renamed mouse/underglow keycodes. Map legacy names when missing
// so the same keymap builds on both old and new QMK trees.
#if !defined(KC_BTN1)
#  if defined(MS_BTN1)
#    define KC_BTN1 MS_BTN1
#    define KC_BTN2 MS_BTN2
#    define KC_BTN3 MS_BTN3
#    define KC_BTN4 MS_BTN4
#    define KC_BTN5 MS_BTN5
#  else
#    define KC_BTN1 KC_NO
#    define KC_BTN2 KC_NO
#    define KC_BTN3 KC_NO
#    define KC_BTN4 KC_NO
#    define KC_BTN5 KC_NO
#  endif
#endif

#if !defined(KC_WH_U)
#  if defined(MS_WHLU)
#    define KC_WH_U MS_WHLU
#    define KC_WH_D MS_WHLD
#    define KC_WH_L MS_WHLL
#    define KC_WH_R MS_WHLR
#  else
#    define KC_WH_U KC_NO
#    define KC_WH_D KC_NO
#    define KC_WH_L KC_NO
#    define KC_WH_R KC_NO
#  endif
#endif

#if !defined(KC_MS_U)
#  if defined(MS_UP)
#    define KC_MS_U MS_UP
#    define KC_MS_D MS_DOWN
#    define KC_MS_L MS_LEFT
#    define KC_MS_R MS_RGHT
#  else
#    define KC_MS_U KC_NO
#    define KC_MS_D KC_NO
#    define KC_MS_L KC_NO
#    define KC_MS_R KC_NO
#  endif
#endif

#if !defined(RGB_TOG)
#  if defined(UG_TOGG)
#    define RGB_TOG UG_TOGG
#    define RGB_MOD UG_NEXT
#    define RGB_RMOD UG_PREV
#    define RGB_HUI UG_HUEU
#    define RGB_HUD UG_HUED
#    define RGB_SAI UG_SATU
#    define RGB_SAD UG_SATD
#    define RGB_VAI UG_VALU
#    define RGB_VAD UG_VALD
#    define RGB_SPI UG_SPDU
#    define RGB_SPD UG_SPDD
#  else
#    define RGB_TOG KC_NO
#    define RGB_MOD KC_NO
#    define RGB_RMOD KC_NO
#    define RGB_HUI KC_NO
#    define RGB_HUD KC_NO
#    define RGB_SAI KC_NO
#    define RGB_SAD KC_NO
#    define RGB_VAI KC_NO
#    define RGB_VAD KC_NO
#    define RGB_SPI KC_NO
#    define RGB_SPD KC_NO
#  endif
#endif

#if !defined(MS_BTN1) && defined(KC_BTN1)
#  define MS_BTN1 KC_BTN1
#  define MS_BTN2 KC_BTN2
#  define MS_BTN3 KC_BTN3
#  define MS_BTN4 KC_BTN4
#  define MS_BTN5 KC_BTN5
#endif

#if !defined(MS_WHLU) && defined(KC_WH_U)
#  define MS_WHLU KC_WH_U
#  define MS_WHLD KC_WH_D
#  define MS_WHLL KC_WH_L
#  define MS_WHLR KC_WH_R
#endif

#if !defined(MS_UP) && defined(KC_MS_U)
#  define MS_UP   KC_MS_U
#  define MS_DOWN KC_MS_D
#  define MS_LEFT KC_MS_L
#  define MS_RGHT KC_MS_R
#endif

#if !defined(UG_TOGG) && defined(RGB_TOG)
#  define UG_TOGG RGB_TOG
#  define UG_NEXT RGB_MOD
#  define UG_PREV RGB_RMOD
#  define UG_HUEU RGB_HUI
#  define UG_HUED RGB_HUD
#  define UG_SATU RGB_SAI
#  define UG_SATD RGB_SAD
#  define UG_VALU RGB_VAI
#  define UG_VALD RGB_VAD
#  define UG_SPDU RGB_SPI
#  define UG_SPDD RGB_SPD
#endif

// ── Layer indices ─────────────────────────────────────────
enum layers {
    _BASE = 0,
    _FN,
    _LAYER2,
    _LAYER3,
};

// ── Keymaps ───────────────────────────────────────────────
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_BASE] = LAYOUT(
        KC_MUTE, KC_BTN3,
        KC_NUM, KC_PSLS, KC_PAST, KC_PMNS,
        KC_P7, KC_P8, KC_P9, KC_PPLS,
        KC_P4, KC_P5, KC_P6,
        KC_P1, KC_P2, KC_P3, KC_PENT,
        KC_P0,           KC_PDOT
    ),

    [_FN] = LAYOUT(
        KC_TRNS, KC_TRNS,
        MO(1), KC_F1, KC_F2, RGB_TOG,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    ),

    [_LAYER2] = LAYOUT(
        KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    ),

    [_LAYER3] = LAYOUT(
        KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    )
};


#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_BASE] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(MS_WHLU, MS_WHLD) },
    [_FN] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [_LAYER2] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [_LAYER3] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) }
};
#endif



static int8_t oled_vol = 5; // 0-10, tracked via encoder










oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_0;
}

bool oled_task_user(void) {
    // Let the board's candypad_oled.c render the default dashboard
    return true; // true = let board render default dashboard, false = we handled it ourselves
}

bool candypad_render_default_user(void) {



    // Volume bar
    oled_set_cursor(0, 3);
    oled_write_P(PSTR("VOL "), false);
    for (uint8_t i = 0; i < 10; i++) {
        oled_write_char(i < oled_vol ? 0xFF : '-', false);
    }


    return false; // false = let board continue with its default rendering
}


