// Generated by the CandyPad editor. The body between the markers is yours.
#include QMK_KEYBOARD_H

#ifdef OLED_ENABLE
bool candypad_render_default_user(void) {
// >>> editor-generated
    // The board keeps its line helpers static to its own file; macros instead,
    // since this box is a function body.
#define DRAW_H(x, y, len, on) do { for (uint8_t i_ = 0; i_ < (len); i_++) oled_write_pixel((i_) + (x), (y), (on)); } while (0)
#define DRAW_V(x, y, len, on) do { for (uint8_t i_ = 0; i_ < (len); i_++) oled_write_pixel((x), (i_) + (y), (on)); } while (0)

    // Declared in keymap_introspection.h, which QMK_KEYBOARD_H does not pull in.
    uint16_t keycode_at_encodermap_location(uint8_t layer_num, uint8_t encoder_idx, bool clockwise);

    static char s_u_d[4] = {24, 38, 25, 0}; // up/down glyphs in the OLED font
    static char s_l_r[4] = {27, 38, 26, 0}; // left/right
    bool on;

    // --- Layer ---
    oled_set_cursor(0, 1);
    oled_write_P(PSTR("LAYER"), false);
    oled_set_cursor(6, 1);
    oled_write_char(get_highest_layer(layer_state) + 0x30, true);
    DRAW_H((OLED_FONT_WIDTH * 6) - 1, OLED_FONT_HEIGHT - 1, OLED_FONT_WIDTH + 1, true);
    DRAW_V((OLED_FONT_WIDTH * 6) - 1, OLED_FONT_HEIGHT, OLED_FONT_HEIGHT, true);

    // --- Encoders (the two blocks differ only by index and row) ---
    for (uint8_t e = 0; e < 2; e++) {
        uint8_t  row     = 1 + (e * 2);
        uint8_t  layer   = get_highest_layer(layer_state);
        uint16_t keycode = KC_TRNS;

        while (keycode == KC_TRNS) { // fall through transparent layers
            keycode = keycode_at_encodermap_location(layer, e, true); // clockwise only
            if (keycode == KC_TRNS) {
                if (layer > 0) {
                    layer--;
                } else {
                    keycode = KC_NO;
                }
            }
        }

        char *label;
        switch (keycode) {
            case KC_NO:               label = " - ";  break;
            case KC_WH_U:
            case KC_WH_D:             label = "WHL";  break;
            case KC_VOLD:
            case KC_VOLU:             label = "VOL";  break;
            case KC_MEDIA_NEXT_TRACK:
            case KC_MEDIA_PREV_TRACK: label = "MED";  break;
            case KC_UP:
            case KC_DOWN:             label = s_u_d; break;
            case KC_LEFT:
            case KC_RIGHT:            label = s_l_r; break;
            default:                  label = "Usr";  break;
        }

        oled_set_cursor(13, row);
        oled_write_P(e ? PSTR("ENC2") : PSTR("ENC1"), false);
        oled_set_cursor(18, row);
        oled_write(label, true);
        DRAW_H((OLED_FONT_WIDTH * 18) - 1, (OLED_FONT_HEIGHT * row) - 1, (OLED_FONT_WIDTH * 3) + 1, true);
        DRAW_V((OLED_FONT_WIDTH * 18) - 1, OLED_FONT_HEIGHT * row, O
    }

    // --- Lock keys ---
    led_t led_state = host_keyboard_led_state();
    oled_set_cursor(4, 3);
    if (led_state.caps_lock && !led_state.num_lock) { // caps transc
        oled_write_P(PSTR("CAP"), true);
    } else {
        oled_write_P(PSTR("NUM"), led_state.num_lock);
    }
    on = led_state.num_lock || led_state.caps_lock;
    DRAW_H((OLED_FONT_WIDTH * 4) - 1, (OLED_FONT_HEIGHT * 3) - 1, (On);
    DRAW_V((OLED_FONT_WIDTH * 4) - 1, OLED_FONT_HEIGHT * 3, OLED_FONT_HEIGHT, on);

    // --- Matrix mini-map ---
#define MXDS_X 2
#define MXDS_Y ((OLED_FONT_HEIGHT * 3) + 1)

    for (uint8_t yy = 0; yy < MATRIX_ROWS; yy++) {
        for (uint8_t xx = 0; xx < MATRIX_COLS; xx++) {
            if ((xx == 2 && yy == 3) || (xx == 4 && (yy == 0 || yy == 3))) {
                continue; // 2U keys and knobs, drawn below
            }
            on = (matrix_get_row(yy) & (1 << xx)) > 0;
            oled_write_pixel(MXDS_X + xx, MXDS_Y + yy, on);
        }
    }

    on = (matrix_get_row(1) & (1 << 3)) > 0; // `+`
    oled_write_pixel(MXDS_X + 3, MXDS_Y + 2, on);
    on = (matrix_get_row(3) & (1 << 3)) > 0; // Enter
    oled_write_pixel(MXDS_X + 3, MXDS_Y + 4, on);
    on = (matrix_get_row(4) & (1 << 1)) > 0; // `0`
    oled_write_pixel(MXDS_X, MXDS_Y + 4, on);
    on = (matrix_get_row(2) & (1 << 3)) > 0; // Enc 1 press
    oled_write_pixel(MXDS_X + 2, MXDS_Y - 1, on);
    on = (matrix_get_row(4) & (1 << 3)) > 0; // Enc 2 press
    oled_write_pixel(MXDS_X + 3, MXDS_Y - 1, on);

    DRAW_H(MXDS_X - 2, MXDS_Y - 1, 8, true);
    DRAW_H(MXDS_X - 2, MXDS_Y + 6, 8, true);
    DRAW_V(MXDS_X - 2, MXDS_Y, 8, true);
    DRAW_V(MXDS_X + 5, MXDS_Y, 8, true);

#undef MXDS_X
#undef MXDS_Y
#undef DRAW_H
#undef DRAW_V

    return true; // handled here; the board skips its own rendering
// <<< editor-generated
}
#endif
