# Generated by Candypad Configurator
# https://docs.qmk.fm

OLED_ENABLE        = yes
ENCODER_ENABLE     = yes
ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE    = no
RGBLIGHT_ENABLE    = no
WPM_ENABLE         = no
RAW_ENABLE         = no

# Keep firmware size in check
LTO_ENABLE         = yes
